name: Test

on:
  push:
    branches-ignore: [ "main" ]

env:
  NODE_VERSION: ">=20.15.0"
  SKIP_ENV_VALIDATION: true

permissions:
  id-token: write
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
          submodules: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: npm
      - name: Install Dependencies
        run: |
          npm install --frozen-lockfile
      - name: Lint
        run: npm run lint
      - name: Validate Build
        run: npm run build
