import { ClerkProvider } from '@clerk/nextjs';
import './global.css';

export const metadata = {
  title: 'Welcome to caffeinatedcodebase',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{
        elements: {
          footer: "hidden",
        },
      }}>
      <body>{children}</body>
      </ClerkProvider>
    </html>
  );
}
